image: gradle:8.8-jdk21-alpine

stages:
  - test
  - build

test_project:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop)$/ && $CI_PIPELINE_SOURCE == "push"
      when: always
  script:
    - gradle test --info --stacktrace
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
    paths:
      - build/reports/tests/
      - build/test-results/test/TEST-*.xml
      - build/reports/problems/
    expire_in: 1 hour
    when: always

build_project:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop)$/ && $CI_PIPELINE_SOURCE == "push"
      when: always
  script:
    - gradle clean bootJar --info --stacktrace
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 30 minutes