image: gradle:8.8-jdk21-alpine

stages:
  - test
  - build
  - image_build_and_push

test_project:
  stage: test
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop)$/ && $CI_PIPELINE_SOURCE == "push"
      when: always
  script:
    - gradle test --info --stacktrace
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
    paths:
      - build/reports/tests/
      - build/test-results/test/TEST-*.xml
      - build/reports/problems/
    expire_in: 1 hour
    when: always

test_integration:
  stage: test
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop)$/ && $CI_PIPELINE_SOURCE == "push"
      when: always
  services:
    - name: postgres:17.5
      alias: database
  variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: deliverydb_test
  before_script: 
    - apk add --no-cache postgresql-client netcat-openbsd
    - echo "Esperando o PostgreSQL ficar disponível..."
    - |
      until nc -z database 5432; do
        echo "Aguardando o banco de dados..."
        sleep 2
      done
    - echo "PostgreSQL está disponível!"
  script: 
    - echo "Iniciando testes de integração..."
    - PGPASSWORD="$POSTGRES_PASSWORD" psql -h database -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT version();"
    - echo "Executando testes de integração com o banco de dados..."

build_project:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop)$/ && $CI_PIPELINE_SOURCE == "push"
      when: always
  script:
    - gradle clean bootJar --info --stacktrace
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 30 minutes

docker_build_and_push:
  stage: image_build_and_push
  image: docker:24-cli
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|develop)$/ && $CI_PIPELINE_SOURCE == "push"
      when: always
  services:
    - name: docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_DRIVER: overlay2
    DOCKER_ORGANIZATION: algaworks
    DOCKER_REPOSITORY_NAME: delivery-tracking
  before_script:
    - echo "Fazendo login no Docker Hub..."
    - echo "$DOCKER_SECRET" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker info
    - docker --version
  script:
    - echo "Construindo a imagem Docker..."
    - docker build -t $DOCKER_ORGANIZATION/$DOCKER_REPOSITORY_NAME:latest .
    - echo "Enviando a imagem Docker para o Docker Hub..."  
    - docker push $DOCKER_ORGANIZATION/$DOCKER_REPOSITORY_NAME:latest
    - echo "Imagem Docker enviada com sucesso!"