image: gradle:8.8-jdk21-alpine

stages:
  - prepare_version
  - test
  - build
  - build_and_push
  - semantic_release

.install-semantic-release-deps: &install_semantic_release_deps
  - echo "Instalando dependências do Semantic Release..."
  - apk add --no-cache git
  - |
    npm install -g semantic-release@24.0.0 \
    @semantic-release/commit-analyzer@13.0.0 \
    @semantic-release/release-notes-generator@14.0.0 \
    @semantic-release/changelog@6.0.3 \
    @semantic-release/gitlab@13.1.0 \
    @semantic-release/exec@6.0.3 \
    @semantic-release/git@10.0.1 \
    conventional-changelog-conventionalcommits@8.0.0 \
    conventional-changelog-cli@5.0.0

.rules-standard: &rules-standard
  - if: $CI_COMMIT_BRANCH =~ /^(main|develop)$/ && $CI_PIPELINE_SOURCE == "push"
    when: always

prepare_version:
  image: node:22-alpine
  stage: prepare_version
  rules: *rules-standard
  before_script:
    - *install_semantic_release_deps
  script: 
    - echo "Preparando a versão do projeto..."
    - semantic-release --dry-run --no-ci
    - |
      if [ ! -e .VERSION ]; then 
        echo "canary" > .VERSION 
      else 
        echo "Arquivo .VERSION já existe."
      fi

    - echo "Declarando variaveis de ambiente..."
    - echo "NEXT_VERSION=$(cat .VERSION)" >> build.env
  artifacts:
    reports:
      dotenv: build.env

test_project:
  stage: test
  rules: *rules-standard
  script:
    - gradle test --info --stacktrace
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
    paths:
      - build/reports/tests/
      - build/test-results/test/TEST-*.xml
      - build/reports/problems/
    expire_in: 1 hour
    when: always

test_integration:
  stage: test
  image: alpine:latest
  rules: *rules-standard
  services:
    - name: postgres:17.5
      alias: database
  variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: deliverydb_test
  before_script: 
    - apk add --no-cache postgresql-client netcat-openbsd
    - echo "Esperando o PostgreSQL ficar disponível..."
    - |
      until nc -z database 5432; do
        echo "Aguardando o banco de dados..."
        sleep 2
      done
    - echo "PostgreSQL está disponível!"
  script: 
    - echo "Iniciando testes de integração..."
    - PGPASSWORD="$POSTGRES_PASSWORD" psql -h database -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT version();"
    - echo "Executando testes de integração com o banco de dados..."

build_project:
  stage: build
  rules: *rules-standard
  script:
    - gradle clean bootJar --info --stacktrace -Pversion=${NEXT_VERSION:-canary}
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 30 minutes

build_and_push:
  stage: build_and_push
  image: docker:24-cli
  rules: *rules-standard
  services:
    - name: docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_DRIVER: overlay2
    DOCKER_ORGANIZATION: algaworks
    DOCKER_REPOSITORY_NAME: delivery-tracking
  before_script:
    - echo "Fazendo login no Docker Hub..."
    - echo "$DOCKER_SECRET" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker info
    - docker --version
  script:
    - echo "Construindo a imagem Docker..."
    - docker build -t $DOCKER_ORGANIZATION/$DOCKER_REPOSITORY_NAME:${NEXT_VERSION:-canary} .
    - echo "Enviando a imagem Docker para o Docker Hub..."  
    - docker push $DOCKER_ORGANIZATION/$DOCKER_REPOSITORY_NAME:${NEXT_VERSION:-canary}
    - echo "Imagem Docker enviada com sucesso!"

semantic_release:
  image: node:22-alpine
  stage: semantic_release
  rules: *rules-standard
  before_script:
    - *install_semantic_release_deps
  script: 
    - echo "Executando o Semantic Release..."
    - semantic-release --no-ci